sudo: false
language: node_js
cache:
  yarn: true
node_js:
  - '10'
install:
  - yarn global add codecov
  - yarn
before_script:
  - rm -rf ./coverage
script:
  - yarn build
  - yarn coverage
  - codecov
